import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";

const fonts = localFont({
  src: [
    {
      path: "../public/Satoshi-Medium.woff2",
      weight: "400",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col overflow-x-hidden min-h-screen max-w-screen bg-gray-900 text-white text-[0.9em] tracking-[0.02em] ${fonts.className}`}
      >
        <main className="flex-auto p-4 md:p-14">{children}</main>
      </body>
    </html>
  );
}
